- name: Get process ID for a specific port
  hosts:  "{{ target_host }}"
  tasks:
    - name: Set portNum variable
      set_fact:
        portNum: 80

    - name: Get process ID
      shell: >
        netstat -tunlp | grep ":{{ portNum }} " |
        awk -F'[ /]+' '{ for(i=0;i<NF;i++){ if($i=="LISTEN"){ print $(i+1);break} } }' |
        head -n 1
      register: processID

    - name: Print process ID
      debug:
        msg: "{{ processID.stdout }}"

#    - name: Get jobName
#      shell: >
#        dpa list | grep {{ processID.stdout }} |
#        awk -F"[ ']+" '{print $2}'
#      register: jobName
#
#    - name: Print jobName
#      debug:
#        msg: "{{ jobName.stdout }}"
#
#    - name: Change to job directory
#      shell: >
#        cd $(dpa status {{ jobName.stdout }} |
#        grep "WorkingDir" | awk -F'[ ":]+' '{print $3}')
#
#    - name: Print user from .apollo file
#      shell: >
#        cat .apollo | egrep "user:" | awk '{print $2}'
#
